// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using HotelManagementProjectfeb.Data;

#nullable disable

namespace ZzzProject.Migrations
{
    [DbContext(typeof(ZzzDbContext))]
    [Migration("20230223105605_Confirm")]
    partial class Confirm
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ZzzProject.Model.Domain.Bill", b =>
                {
                    b.Property<Guid>("Bill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Reservation_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Reservationsreservation_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Room_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Roomsroom_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("stay_dates")
                        .HasColumnType("int");

                    b.Property<decimal>("total_bill")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Bill_id");

                    b.HasIndex("Reservationsreservation_id");

                    b.HasIndex("Roomsroom_id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Guest", b =>
                {
                    b.Property<Guid>("Guest_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guest_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone_number")
                        .HasColumnType("bigint");

                    b.HasKey("Guest_id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Inventory", b =>
                {
                    b.Property<Guid>("Inventory_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Inventory_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Inventory_Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Reservation", b =>
                {
                    b.Property<Guid>("reservation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Check_in")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Check_out")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guest_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GuestsGuest_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Room_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Roomsroom_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("no_of_adults")
                        .HasColumnType("int");

                    b.Property<int>("no_of_children")
                        .HasColumnType("int");

                    b.Property<int>("no_of_nights")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("reservation_id");

                    b.HasIndex("GuestsGuest_id");

                    b.HasIndex("Roomsroom_id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Room", b =>
                {
                    b.Property<Guid>("room_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("room_rate")
                        .HasColumnType("float");

                    b.Property<bool>("room_status")
                        .HasColumnType("bit");

                    b.HasKey("room_id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.User_Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Users_Roles");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Bill", b =>
                {
                    b.HasOne("ZzzProject.Model.Domain.Reservation", "Reservations")
                        .WithMany("Bills")
                        .HasForeignKey("Reservationsreservation_id");

                    b.HasOne("ZzzProject.Model.Domain.Room", "Rooms")
                        .WithMany("Bills")
                        .HasForeignKey("Roomsroom_id");

                    b.Navigation("Reservations");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Reservation", b =>
                {
                    b.HasOne("ZzzProject.Model.Domain.Guest", "Guests")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestsGuest_id");

                    b.HasOne("ZzzProject.Model.Domain.Room", "Rooms")
                        .WithMany("Reservations")
                        .HasForeignKey("Roomsroom_id");

                    b.Navigation("Guests");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.User_Roles", b =>
                {
                    b.HasOne("ZzzProject.Model.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZzzProject.Model.Domain.Staff", "Staffs")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Guest", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Reservation", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Room", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ZzzProject.Model.Domain.Staff", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
